# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff67dbc9c4032b202db029e128c4a226be7936090b40189d28a7419405241c4354aadf4bed46c069ccef278e0c7cb9535f798b4c4b26612fc1a5900dd9e3fce

test:
  secret_key_base: 2a5258228c1040af96f8ecc060d54f8cfa1ee6ef3b91afdd4b5259faef90c0b76852587cc4cbcc04fc38e59a1ba0921b74952d8dc6c789064566546e8bdb23c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
